#!/usr/bin/env python3
from pathlib import Path
import sys
import zlib


def view_decompressed_objects():
    print('--- show decompressed objects ---')
    path = './sandbox/.nymphaea/objects/'
    objects = Path(path)
    for obj in objects.iterdir():
        with open(obj.absolute(), 'rb') as rb:
            text = rb.read()
        print(f'obj: {obj}')
        print(zlib.decompress(text).decode())
    print('--- end ---')

def main():
    if len(sys.argv) <= 1:
        print('error! no input command.')
        sys.exit(1)
    command = sys.argv[1]
    if command == 'decompress':
        view_decompressed_objects()
    else:
        print('error! inputed command doesn\'t exist.')


if __name__ == '__main__':
    main()
